<?php

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => 'https://app.msfg.finance/refresh-phoneburner-token',
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => '',
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => 'GET',
  CURLOPT_HTTPHEADER => array(
    'Cookie: XSRF-TOKEN=eyJpdiI6IjFTQ3dXdnhBVW5MSE5Ya0gyK2ZXY2c9PSIsInZhbHVlIjoieEFQYko4VmgwU2xUTWhEMEljTEdvTmwxSEN5amo3SjFITnNLVkh6TGJ4UVhOa0hiVEV0SUw2d2lReUxHSVJMTmtWRzRoOElLRURHVVlYVlZaNUphUEsvSmQrV0svTjZPYWhWNWtqK1hWWGhzcnBFWU9kVkZva3pZY0FXQ0VKYlEiLCJtYWMiOiJjMzFkMjI2ZGFhNmY0ZjllY2E5M2I3M2ExNGYwOGYzMGU3YmE1MjJhMmU2MDNiODA5MjZkODMxOWY1NGVmZjNiIiwidGFnIjoiIn0%3D; msfgfinance_session=eyJpdiI6ImlrUndUSXNTc29SU3VkU3c3RTlYY0E9PSIsInZhbHVlIjoiSTdWZlVVeTYxRnh4N3M1SmxhL2xuOXFOcDdpU2I1N0c3SmZrVUgxNTlENHZEWlJuQnFMMDh0THpKaWQyMGw2YVlHSHN2SENDcjdJQkJLMEp2M0Z5VkZwTnJKaVBVYlY2QnZhdFF3KytJeFQ2cHd2WitLVWZVaUE3RW93SVVHWEsiLCJtYWMiOiJkMTVhYTEzOTc1YmFiNDk0N2I1NGYwNmQ0NTZmYzQ2NTY5YzJjMzQ4ZjhkN2IwMWM1YTRhMGVmOTBjMGM1NTZhIiwidGFnIjoiIn0%3D'
  ),
));

$response = curl_exec($curl);

curl_close($curl);
echo $response;
